# Generated by Django 2.2.2 on 2019-07-16 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('backgroundColor', models.CharField(max_length=255)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Publica'), ('PRIVATE', 'Privada'), ('FRIENDS', 'Só para Amigos')], default='PUBLIC', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('y', models.DecimalField(decimal_places=2, max_digits=5)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.Page')),
            ],
        ),
    ]
